- id: gitleaks
  name: Detect hardcoded secrets
  description: Detect hardcoded secrets using Gitleaks
  entry: gitleaks protect --verbose --redact --staged
  language: golang
  pass_filenames: false
