name: gitleaks
on:
  push:
    branches: [CTPROJECT-490-GitLeaks]
  pull_request:
    branches: [CTPROJECT-490-GitLeaks]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2.3.2
